name: Android Release

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  SHELL_REPO: 4332weizi/taro-native-shell
  SHELL_REPO_REF: 0.63.2_origin
  APP_ID: taro.mortgage.calculator
  APP_NAME: Taro Mortgage Caclulator
  APP_VERSION_NAME: 1.0
  APP_VERSION_CODE: 10
  APP_RES: android/res/
  APP_ICON: ic_launcher
  APP_TYPE: release
  APP_ABI_FILTERS: armeabi-v7a, arm64-v8a
  KEYSTORE_FILE: android/keystore.jks
  KEYSTORE_PASSWORD: 123456
  KEYSTORE_KEY_ALIAS: app
  KEYSTORE_KEY_PASSWORD: abcdefg

jobs:
  build-android:
    runs-on: macos-latest
    steps: 
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Checkout Taro Shell Project
        uses: actions/checkout@v2
        with:
          repository: ${{ env.SHELL_REPO }}
          ref: ${{ env.SHELL_REPO_REF }}
          path: taro-native-shell
      - name: Merge Package Dependencies
        run: |
          node ${{ github.workspace }}/.github/merge-package.js \
            ${{ github.workspace }}/package.json \
            ${{ github.workspace }}/taro-native-shell/package.json \
            ${{ github.workspace }}/package.json
          cat ${{ github.workspace }}/package.json
      - name: Get Yarn Cache Directory Path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v2
        env:
          cache-name: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache node_modules Folder
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules
          restore-keys: ${{ runner.os }}-node_modules
      - name: Install Dependencies
        run: |
          yarn install
      - name: Build Taro
        run: |
          yarn build:rn-android
      - name: Upload Taro Products
        uses: actions/upload-artifact@v2
        with:
          name: taro-android-products
          path: dist/rn/android/
      - name: Link node_modules Folder to Shell Project
        run: |
          ln -s $PWD/node_modules $PWD/taro-native-shell/node_modules
      - name: Merge Resources
        run: |
          mv ./dist/rn/android/index.android.bundle ./taro-native-shell/android/app/src/main/assets/index.android.bundle
          if [ ${{ env.APP_ICON }} = ic_launcher ]; then 
            rm ./taro-native-shell/android/app/src/main/res/mipmap-*dpi/ic_launcher.png
          fi
          rsync -a ./dist/rn/android/ ./taro-native-shell/android/app/src/main/res/
          rsync -a ${{ env.APP_RES }}/ ./taro-native-shell/android/app/src/main/res/
      - name: Cache Gradle
        uses: actions/cache@v2
        env:
          cache-name: gradle-cache
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle
          restore-keys: |
            ${{ runner.os }}-gradle
      - name: Assemble Android ${{ env.APP_TYPE }}
        run: |
          cd ./taro-native-shell/android && \
          ./gradlew assemble${{ env.APP_TYPE }} \
            -Papp_id=${{ env.APP_ID }} \
            -Papp_name='${{ env.APP_NAME }}' \
            -Papp_icon=${{env.APP_ICON}} \
            -Pversion_code=${{ env.APP_VERSION_CODE }} \
            -Pversion_name=${{ env.APP_VERSION_NAME }} \
            -Pabi_filters='${{ env.APP_ABI_FILTERS }}' \
            -Pkeystore_file=${{ github.workspace }}/${{ env.KEYSTORE_FILE }} \
            -Pkeystore_password=${{ env.KEYSTORE_PASSWORD }} \
            -Pkeystore_key_alias=${{ env.KEYSTORE_KEY_ALIAS }} \
            -Pkeystore_key_password=${{ env.KEYSTORE_KEY_PASSWORD }}
      - name: Upload Android Products
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ env.APP_TYPE }}
          path: ${{ github.workspace }}/taro-native-shell/android/app/build/outputs/apk/${{ env.APP_TYPE }}/app-${{ env.APP_TYPE }}.apk